version: '3.7'
services:
  db:
    image: 'postgres:16-alpine'
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_NAME=suap
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    command: ["postgres", "-c", "max_locks_per_transaction=1024"]
  web:
    build: .
    environment:
      - DB_NAME=suap
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=db
      - APP_PORT=8080
    depends_on:
      - db
    stdin_open: true
    tty: true      